--Task 2 for Assignment 2

--#1 Insert the following new record to the account table
INSERT into public.account (
	account_firstname,
	account_lastname,
	account_email, 
	account_password
)
VALUES (
	'Tony',
	'Stark',
	'tony@starkent.com',
	'Iam1ronM@n'
);

--#2 Modify the Tony Stark record to change account_type to "Admin"
UPDATE account SET account_type = 'Admin' WHERE account_id = 1;

--#3 Delete the Tony Stark record from the database
DELETE FROM account WHERE account_id = 1;

--#4 Modify the GM Hummer record to read 'a huge interior' rather than 'small interiors' using a single query
UPDATE inventory 
SET inv_description = REPLACE(inv_description, 'the small interiors', 'a huge interior')
WHERE inv_id = 10;

--#5 Use an inner join to select the make and model fields from the inventory table and the classification name field from the classification table for inventory items that belong to the "Sport" category.
SELECT
	inventory.inv_make,
	inventory.inv_model,
	classification.classification_name
FROM inventory
INNER JOIN classification
	ON inventory.classification_id = classification.classification_id
WHERE classification.classification_name = 'Sport';

--#6 Update all records in the inventory table to add "/vehicles" to the middle of the file path in the inv_image and inv_thumbnail columns using a single query.
UPDATE inventory
SET 
	inv_image = REPLACE(inv_image, '/images', '/images/vehicles'),
	inv_thumbnail = REPLACE(inv_thumbnail, '/images', '/images/vehicles');

--Final Assignment. Create a new table for reviews of inventory
CREATE TABLE public.review (
	review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	review_text text NOT NULL,
	review_date timestamp DEFAULT CURRENT_TIMESTAMP,
	inv_id integer NOT NULL,
	account_id integer NOT NULL,
	CONSTRAINT review_pkey PRIMARY KEY (review_id),
	CONSTRAINT fk_inventory FOREIGN KEY (inv_id)
		REFERENCES public.inventory (inv_id)
		ON DELETE CASCADE,
	CONSTRAINT fk_account FOREIGN KEY (account_id)
		REFERENCES public.account (account_id)
		ON DELETE CASCADE
);

ALTER TABLE inventory
ADD CONSTRAINT inventory_classification_fk
FOREIGN KEY (classification_id)
REFERENCES classification(classification_id)
ON DELETE RESTRICT;